### ISSUE TITLE
Peer dependencies require angular 13 for v 1.1.0?

### ISSUE THREAD

**Issue by zanaBizz** [damingerdai/angular-toaster#2]
Hey! 

After recently installing the package I've noticed that it has peerDependencies that require angular 13 packages when the rest of the library is using angular 14? Aren't those also supposed to be bumped onto v14 otherwise if people install it via npm they have to have two versions of angular?

**Comment by damingerdai** [comment]
https://github.com/damingerdai/angular-toaster/releases/tag/v1.2.0
