### ISSUE TITLE
bump angular v17

### ISSUE THREAD

**Issue by DhakeBhavana** [damingerdai/angular-toaster#4]
When library will be upgraded with angular 17

**Comment by damingerdai** [comment]
I will update it

**Comment by damingerdai** [comment]
[angular-toaster@1.4.0](https://www.npmjs.com/package/angular-toaster/v/1.4.) is released

**Comment by DhakeBhavana** [comment]
This is still not resolved. It still uses old verions in peerdependencies.
https://github.com/damingerdai/angular-toaster/blob/develop/packages/angular-toaster/package.json

**Comment by damingerdai** [comment]
[angular-toaster@1.5.0](https://www.npmjs.com/package/angular-toaster/v/1.5.0) is released.
